services:
  # Serwis Bazy Danych
  db:
    image: postgres:15-alpine
    container_name: booking_system_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d database"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serwis Backendu
  backend:
    container_name: booking_system_backend
    build:
      context: ./frontend/api
      dockerfile: Dockerfile
    volumes:
      - ./frontend/api:/app
      - /app/.venv
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin@db:5432/database
      - SECRET_KEY=twoj_bardzo_bezpieczny_sekretny_klucz_zmien_to_koniecznie
    depends_on:
      db:
        condition: service_healthy

  # Serwis Frontendu (serwer deweloperski Vite)
  frontend:
    container_name: booking_system_frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules # Wykluczamy node_modules z volume, aby używać tych z obrazu
    ports:
      - "80:3000" # Wystawiamy port Vite bezpośrednio na 80 w trybie dev
    depends_on:
      - backend

volumes:
  postgres_data:
